# Header
menu:
  首页: /
  文章: /archives
  关于: /about
#rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

swift_search:
    enable: false
# Swiftype Search Key
swiftype_key: cfMrgJ_UF1xJcNuMGgKs

baidu_search:
    enable: false